---
- name: Update cache with key and value
  cache:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
  - { key: 'copy_archive', value: '{{ copy_archive }}' }

- name: Install the local mirror with proxy
  shell: "{{ apigee_service }} apigee-mirror install"
  environment:
    no_proxy: "{{ no_proxy }}"
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"

- name: Sync the local mirror with only new rpms with proxy
  shell: "{{ apigee_service }} apigee-mirror sync --only-new-rpms apigeereleasever={{ apigee_mirror_version | default(opdk_version) }}"
  when: all_rpms is not defined and not all_rpms | bool == True
  environment:
    no_proxy: "{{ no_proxy }}"
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"

- name: Sync the local mirror with all rpms with proxy
  shell: "{{ apigee_service }} apigee-mirror sync apigeereleasever={{ apigee_mirror_version | default(opdk_version) }}"
  when: all_rpms is defined and all_rpms | bool == True
  environment:
    no_proxy: "{{ no_proxy }}"
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"

- name: Create archive with proxy
  shell: "{{ apigee_service }} apigee-mirror package"
  environment:
    no_proxy: "{{ no_proxy }}"
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
