---
- name: Update cache with key and value
  cache:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
  - { key: 'copy_archive', value: '{{ copy_archive }}' }

- name: Uninstall the local mirror
  shell: '/opt/apigee/apigee-service/bin/apigee-service apigee-mirror uninstall'
  args:
    removes: "{{ apigee_home }}/apigee-mirror"
  environment:
    no_proxy: "{{ no_proxy | default('') }}"
    http_proxy: "{{ http_proxy | default('') }}"
    https_proxy: "{{ https_proxy | default('') }}"

#- name: Update apigeereleasever variable for Yum to opdk_version
#  become: yes
#  copy:
#    content: "{{ apigeereleasever }}"
#    dest: /etc/yum/vars/apigeereleasever
#    mode: 600
#    owner: root
#    group: root

- name: Install the local mirror
  shell: '/opt/apigee/apigee-service/bin/apigee-service apigee-mirror install'
  args:
    creates: "{{ apigee_home }}/apigee-mirror"
  environment:
    no_proxy: "{{ no_proxy | default('') }}"
    http_proxy: "{{ http_proxy | default('') }}"
    https_proxy: "{{ https_proxy | default('') }}"

- name: Update apigeereleasever variable for Yum for apigee-mirror sync
  become: yes
  copy:
    content: "{{ apigeereleasever | default(opdk_version) }}"
    dest: /etc/yum/vars/apigeereleasever
    mode: 600
    owner: root
    group: root

- name: Sync the local mirror with only new rpms
  ignore_errors: yes
  shell: "/opt/apigee/apigee-service/bin/apigee-service apigee-mirror sync --only-new-rpms apigeereleasever={{ apigeereleasever | default(opdk_version) }}"
  args:
    removes: "{{ apigee_home }}/apigee-mirror"
  environment:
    no_proxy: "{{ no_proxy | default('') }}"
    http_proxy: "{{ http_proxy | default('') }}"
    https_proxy: "{{ https_proxy | default('') }}"
  when: all_rpms is not defined and not all_rpms | bool == True

- name: Sync the local mirror with all rpms
  ignore_errors: yes
  shell: "/opt/apigee/apigee-service/bin/apigee-service apigee-mirror sync apigeereleasever={{ apigeereleasever | default(opdk_version) }}"
  args:
    removes: "{{ apigee_home }}/apigee-mirror"
  environment:
    no_proxy: "{{ no_proxy | default('') }}"
    http_proxy: "{{ http_proxy | default('') }}"
    https_proxy: "{{ https_proxy | default('') }}"
  when: all_rpms is defined and all_rpms | bool == True

- name: Update with any extra packages that should be transported manually
  become: yes
  shell: "yum reinstall --downloadonly --downloaddir={{ apigee_home }}/data/apigee-mirror/repos/thirdparty/7 {{ archive_extra_packages | join(' ') }}"
  args:
    removes: "{{ apigee_home }}/data/apigee-mirror/repos/thirdparty/7"
  when: archive_extra_packages is defined

- name: Create archive
  shell: "/opt/apigee/apigee-service/bin/apigee-service apigee-mirror package"
  args:
    removes: "{{ apigee_home }}/apigee-mirror"
  environment:
    no_proxy: "{{ no_proxy | default('') }}"
    http_proxy: "{{ http_proxy | default('') }}"
    https_proxy: "{{ https_proxy | default('') }}"
