---
# tasks file for apigee-opdk-setup-local-repository
- name: Install the local mirror with no proxy
  include: with_no_proxy.yml
  when: https_proxy is not defined and http_proxy is not defined

- name: Install the local mirror with no proxy
  include: with_proxy.yml
  when: https_proxy is defined and http_proxy is defined
